export const AUDIO_PRESETS = {
  PLAYER: {
    DAMAGED_NOTE: "C2",
    DAMAGED_DURATION: "8n",
    NOISE_DECAY: 0.1,
    NOISE_VOLUME: -10,
  },
  WEAVER: {
    DAMAGED_NOTE: "E3",
    DAMAGED_DURATION: "16n",
    DRONE_BASE_FREQ: 55,
    DRONE_BERSERK_FREQ: 110,
    DRONE_DEFEATED_FREQ: 30,
    LFO_NORMAL_HZ: 0.2,
    LFO_BERSERK_HZ: 4.0,
    LFO_DEFEATED_HZ: 0.05,
    HARMONICITY_NORMAL: 1.5,
    HARMONICITY_BERSERK: 2.5,
    HARMONICITY_DEFEATED: 1.0,
  }
} as const;
