import fs from 'fs';
import path from 'path';

const rootDir = process.cwd();
const manifest = {};

const includeFiles = [
  'index.html',
  'package.json',
  'tsconfig.json',
  'tsconfig.app.json',
  'tsconfig.node.json',
  'vite.config.ts',
  'eslint.config.js',
  'README.md'
];

const includeDirs = ['src'];

function scanDir(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relPath = path.relative(rootDir, fullPath).replace(/\\/g, '/');

    if (entry.isDirectory()) {
      if (entry.name !== 'node_modules' && entry.name !== 'dist' && entry.name !== '.git') {
        scanDir(fullPath);
      }
    } else if (entry.isFile()) {
      if (entry.name === 'sourceCodeManifest.ts' || entry.name === 'source_code_manifest.json') {
        continue;
      }
      const ext = path.extname(entry.name);
      if (['.ts', '.tsx', '.js', '.jsx', '.css', '.json', '.md', '.txt', '.html', '.glsl'].includes(ext)) {
        const content = fs.readFileSync(fullPath, 'utf8');
        manifest[relPath] = content;
      }
    }
  }
}

for (const file of includeFiles) {
  const fullPath = path.join(rootDir, file);
  if (fs.existsSync(fullPath)) {
    const content = fs.readFileSync(fullPath, 'utf8');
    manifest[file] = content;
  }
}

for (const dir of includeDirs) {
  const fullPath = path.join(rootDir, dir);
  if (fs.existsSync(fullPath)) {
    scanDir(fullPath);
  }
}

fs.mkdirSync(path.join(rootDir, 'public'), { recursive: true });
fs.writeFileSync(
  path.join(rootDir, 'public/source_code_manifest.json'),
  JSON.stringify(manifest, null, 2),
  'utf8'
);

fs.mkdirSync(path.join(rootDir, 'src/core'), { recursive: true });
const tsContent = `// Automatically generated by scripts/generate_manifest.js. Do not edit directly.\nexport const sourceCodeManifest: Record<string, string> = ${JSON.stringify(manifest, null, 2)};\n`;
fs.writeFileSync(
  path.join(rootDir, 'src/core/sourceCodeManifest.ts'),
  tsContent,
  'utf8'
);

console.log('Manifest and dynamic source assets compiled successfully.');
