export const CANONICAL_UNITS = {
  SPATIAL: {
    METERS_PER_UNIT: 1.0
  },
  TEMPORAL: {
    LEGACY_FPS_BASIS: 60.0
  },
  GRAVITY: {
    PHYSICAL_EARTH: -9.81,
    PLAYER_KINEMATIC: -24.0,
    JUICE_PARTICLE: -18.0
  },
  TETHER_STRAIN: {
    OVERLOAD_LIMIT: 0.8,
    SNAP_LIMIT: 1.0,
    SNAP_DELAY_SECONDS: 2.6
  },
  SCROLL_MAPPING: {
    TOTAL_RANGE: 140.0,
    BOTTOM_BOUNDARY: -56.0,
    TOP_BOUNDARY: 84.0
  }
} as const;

export const ARENA_CONFIG = {
  HORIZONTAL: {
    WALL_LIMIT_X: 14.2,
    WALL_CLING_THRESHOLD_X: 13.6,
    WALL_GEOMETRY_X: 16.0,
    TICK_GEOMETRY_X: 14.9,
    PLAY_AREA_HALF_WIDTH: 15.0
  },
  VERTICAL: {
    FLOOR_Y: -8.0,
    CEILING_Y: 38.0,
    WEAVER_CEILING_Y: 34.0,
    WEAVER_CEILING_RETURN_Y: 34.0,
    WALL_GEOMETRY_HEIGHT: 140.0,
    TOTAL_SCROLL_RANGE: 140.0,
    PLAYER_SPAWN_Y: 10.0,
    WEAVER_SPAWN_Y: 34.0
  },
  ENTITY: {
    PLAYER_HEIGHT: 1.8,
    PLAYER_RADIUS: 0.4,
    PLAYER_HALF_HEIGHT: 0.9,
    WEAVER_RADIUS: 4.4,
    WEAVER_ICOSPHERE_SUBDIVISIONS: 5,
    PLAYER_CAPSULE_SUBDIVISIONS: 3
  },
  ENTITY_COLORS: {
    WEAVER_ALBEDO: { r: 0.1, g: 0.0, b: 0.2 },
    PLAYER_ALBEDO: { r: 0.95, g: 0.95, b: 1.0 },
    PLAYER_SHEEN: { r: 1.0, g: 0.0, b: 0.5 }
  },
  ENTITY_SPAWNER: {
    WEAVER_INITIAL_VELOCITY_X: 4.5,
    WEAVER_PHYSICS_MASS: 100.0,
    PLAYER_PHYSICS_MASS: 10.0
  },
  PROJECTILE: {
    OFFSCREEN_MIN_Y: -15.0,
    OFFSCREEN_MAX_Y: 42.0
  },
  TETHER: {
    MAX_LENGTH: 24.0,
    INITIAL_LENGTH: 12.0
  },
  SCROLL_SPEED: {
    BASE: 9.0,
    BERSERK: 15.0,
    DASH_MULTIPLIER: 0.45
  }
} as const;

export const GAMEPLAY_TUNING = {
  PLAYER: {
    MAX_INTEGRITY: 5,
    TENSION_DECAY_RATE: 4.0,
    STRAIN_RUMBLE_SCALE: 0.25,
    SWING_STEER_FORCE: 36.0,
    LAUNCH_STEER_FORCE: 16.0,
    TENSION_CHARGE_RATE: 0.38,
    MIN_FLING_TENSION: 0.06,
    FLING_IMPULSE: 76.0,
    LAUNCH_DURATION: 0.7,
    LAUNCH_GRAVITY_MULT: 0.22,
    SCALE_INTERP_RATE: 15.0,
    SLERP_FACTOR: 0.22,
    DRAG_DAMPING: 0.99,
    SQUASH_STRETCH: {
      WALL_SLIDE_X: 0.75,
      WALL_SLIDE_Y: 1.15,
      WALL_SLIDE_Z: 1.0,
      LAUNCH_POWER_MULT: 0.35,
      AIRBORNE_STRETCH_MAX: 0.3,
      AIRBORNE_SPEED_BASIS: 30.0,
      SQUASH_LAND_X: 1.22,
      SQUASH_LAND_Y: 0.72,
      SQUASH_LAND_Z: 1.22,
      SQUASH_WALL_X: 0.72,
      SQUASH_WALL_Y: 1.22,
      LAND_VEL_THRESHOLD: -1.0
    }
  },
  COMBAT: {
    FLING_DAMAGE_THRESHOLD: 0.72,
    WEAVER_CONTACT_DAMAGE: 1,
    PLAYER_IFRAME_DURATION: 1.2,
    PLAYER_FLING_DAMAGE: 35,
    KNOCKBACK_FORCE_X: 16.0,
    KNOCKBACK_FORCE_Y: 16.0,
    KNOCKBACK_BONUS_Y: 8.0,
    REBOUND_FORCE: 22.0,
    BOUNCE_ELASTICITY_MULT: 1.3,
    BROADPHASE_MARGIN: 0.4,
    HITSTOP_PLAYER: 0.08,
    HITSTOP_WEAVER: 0.15
  },
  REEL: {
    MIN_LENGTH: 7.0,
    MAX_LENGTH: 120.0,
    IN_SPEED: 10.0,
    OUT_SPEED: 14.0,
    AUTO_SLACK_TAKEUP_SPEED: 3.0,
    MAX_REEL_ACCEL: 28.0,
    REEL_IN_TENSION_RATE: 0.35,
    REEL_OUT_TENSION_RELIEF: 0.55,
    WALL_SLIDE_PASSIVE_TENSION_RATE: 0.36,
    SWEET_SPOT_MIN: 0.55,
    SWEET_SPOT_MAX: 0.85
  }
} as const;

export const WEAVER_AI_TUNING = {
  BERSERK_HP_THRESHOLD: 0.5,
  PATROL: {
    SPEED_NORMAL: 4.5,
    SPEED_BERSERK: 9.0
  },
  SHOOT: {
    POOL_SIZE: 16,
    TELEGRAPH_TIME: 1.4,
    RELOAD_TIME: 2.4,
    OFFSET_Y: 1.8,
    SPEED: 15.0,
    MAX_LIFE: 8.0,
    PROJECTILE_DIAMETER: 1.8,
    CAMERA_SHAKE_AMP: 0.6,
    CAMERA_SHAKE_DUR: 0.35
  },
  DASH: {
    PREP_TIME: 0.6,
    THRUST_TIME: 0.8,
    RECOVER_TIME: 0.5,
    SPEED_NORMAL: 28.0,
    SPEED_BERSERK: 36.0,
    STROBE_FREQ: 16.0,
    SPEED_THRESHOLD: 0.1,
    COLLISION_GRACE_TIME: 0.15,
    SQUASH_STRETCH: {
      PREP_X: 1.15,
      PREP_Y: 0.82,
      PREP_Z: 1.15,
      STRETCH_MAX: 0.25,
      STRETCH_SPEED_BASIS: 36.0
    },
    CAMERA_SHAKE_PREP_AMP: 0.08,
    CAMERA_SHAKE_PREP_DUR: 0.05,
    CAMERA_SHAKE_PREP_FREQ: 0.4
  },
  RETURN: {
    SPEED: 12.0,
    THRESHOLD: 0.3,
    SQUASH_STRETCH: {
      Y: 1.08,
      X: 0.96
    }
  },
  DEFEATED: {
    SCALE: 0.2
  },
  ANIMATION: {
    LERP_RATE: 12.0,
    PULSE_BASE: 0.04,
    PULSE_FREQ: 3.5,
    YAW_PITCH_ROLL_FREQ: 2.0,
    YAW_PITCH_ROLL_AMP: 0.1,
    ROLL_ANGLE_SCALE: -0.02
  }
} as const;

export const VISUAL_JUICE_CONFIG = {
  WEAVER_COLORS: {
    SWEEPING: "121212",
    DASH_PREP: "dffe00",
    DASH_THRUST: "ff007f",
    DASH_RECOVER: "ff007f",
    RETURNING: "ff007f",
    DEFEATED: "000000"
  },
  MATERIALS: {
    WEAVER: {
      METALLIC: 0.98,
      ROUGHNESS: 0.08,
      CLEAR_COAT_INTENSITY: 0.85,
      CLEAR_COAT_ROUGHNESS: 0.05
    },
    PLAYER: {
      METALLIC: 0.92,
      ROUGHNESS: 0.1,
      SHEEN_INTENSITY: 0.85,
      SHEEN_ROUGHNESS: 0.15
    },
    PROJECTILE: {
      METALLIC: 0.95,
      ROUGHNESS: 0.05,
      SHEEN_INTENSITY: 0.9,
      SHEEN_ROUGHNESS: 0.1
    }
  },
  TETHER_ROPE: {
    SEGMENTS: 24,
    MAX_SAG: 3.8,
    BASE_RADIUS: 0.07,
    MAX_RADIUS: 0.13,
    TENSION_VIB_FREQ: 0.025,
    TENSION_VIB_THRESHOLD: 0.7,
    TENSION_VIB_AMP: 0.35,
    WAVINESS_FREQ: 0.005,
    WAVINESS_AMP: 0.12,
    WAVINESS_STRETCH: 2.5,
    BEZIER_DEPTH: 0.35,
    MAX_SNAP_DURATION_SECONDS: 1.5
  },
  PARTICLES: {
    DRAG: 0.92,
    COLORS: {
      PLAYER_SPARK: { r: 1.0, g: 1.0, b: 1.0 },
      WEAVER_SPARK: { r: 1.0, g: 0.0, b: 0.5 },
      LANDING_DUST: { r: 0.87, g: 0.99, b: 0.0 },
      WALL_SPARK: { r: 1.0, g: 0.0, b: 0.5 },
      PROJECTILE_SPLAT: { r: 1.0, g: 1.0, b: 1.0 }
    },
    BURST: {
      PLAYER: {
        COUNT: 15,
        VELOCITY_Y_MIN: 4.0,
        VELOCITY_Y_MAX: 12.0,
        VELOCITY_Z_MAX: 4.0,
        VELOCITY_SPEED_MIN: 3.0,
        VELOCITY_SPEED_MAX: 8.0,
        LIFE_MIN: 0.3,
        LIFE_MAX: 0.7
      },
      WEAVER: {
        COUNT: 20,
        VELOCITY_Y_MIN: 4.0,
        VELOCITY_Y_MAX: 12.0,
        VELOCITY_Z_MAX: 4.0,
        VELOCITY_SPEED_MIN: 3.0,
        VELOCITY_SPEED_MAX: 8.0,
        LIFE_MIN: 0.3,
        LIFE_MAX: 0.7
      },
      LANDING: {
        COUNT: 12,
        VELOCITY_X_MAX: 6.0,
        VELOCITY_Y_MAX: 1.5,
        VELOCITY_Z_MAX: 1.5,
        LIFE_MIN: 0.4,
        LIFE_MAX: 0.7
      },
      WALL: {
        COUNT: 8,
        VELOCITY_X_MIN: 4.0,
        VELOCITY_X_MAX: 10.0,
        VELOCITY_Y_MAX: 5.0,
        VELOCITY_Z_MAX: 2.0,
        LIFE_MIN: 0.25,
        LIFE_MAX: 0.5
      },
      PROJECTILE: {
        COUNT: 10,
        SPEED_MIN: 2.0,
        SPEED_MAX: 6.0,
        VELOCITY_Z_MAX: 2.0,
        LIFE_MIN: 0.3,
        LIFE_MAX: 0.6
      },
      TRAIL: {
        LIFE_MIN: 0.22,
        LIFE_MAX: 0.34,
        OFFSET_X: 0.3,
        OFFSET_Y: 0.8,
        VELOCITY_X_MAX: 1.2,
        VELOCITY_Y_MAX: 1.2,
        VELOCITY_Z_MAX: 1.0
      }
    },
    DEBRIS: {
      COUNT: 12,
      SIZE_MIN: 1.0,
      SIZE_MAX: 2.5,
      MASS: 3.0,
      FRICTION: 0.5,
      RESTITUTION: 0.2,
      LIFE: 5.0,
      VELOCITY_X_MAX: 18.0,
      VELOCITY_Y_MIN: 5.0,
      VELOCITY_Y_MAX: 19.0,
      VELOCITY_Z_MAX: 8.0,
      ANGULAR_MAX: 12.0,
      Z_FORCE_CLAMP: 0.01,
      SCALE_DECAY_TIME: 1.5
    }
  },
  EMISSIVE: {
    SCROLL_LERP_FACTOR: 0.15,
    PLAYER_LERP_RATE: 0.18,
    PLAYER_EMISSIVE_SCALE: 0.8,
    WEAVER_EMISSIVE_SCALE: 0.95,
    WEAVER_EMISSIVE_PULSE_BASE: 0.1,
    WEAVER_EMISSIVE_PULSE_AMP: 0.08,
    WEAVER_EMISSIVE_PULSE_FREQ: 0.01,
    PLAYER_EMISSIVE_SLIDE: {
      BASE_R: 0.9,
      RANGE_R: 0.1,
      BASE_G: 0.0,
      RANGE_G: 0.0,
      MULT_B: 0.5
    },
    PLAYER_EMISSIVE_LAUNCH: {
      R: 0.95,
      G: 0.95,
      B: 0.95
    },
    PLAYER_EMISSIVE_DEFAULT: {
      R: 0.1,
      G: 0.0,
      B: 0.2
    }
  }
} as const;

export const CAMERA_TUNING = {
  LOWER_COMFORT_Y: -11.5,
  UPPER_COMFORT_Y: 8.0,
  WALL_SLIDE_LERP: 0.12,
  NORMAL_LERP: 0.06,
  MIN_SCROLL_Y: -80.0,
  MAX_SCROLL_Y: 0.0
} as const;

export const POST_PROCESSING_PRESETS = {
  RENDERER: {
    SAMPLES: 4,
    BLOOM_THRESHOLD: 0.45,
    BLOOM_WEIGHT: 1.35,
    BLOOM_KERNEL: 64,
    VIGNETTE_WEIGHT: 3.2,
    EXPOSURE: 1.05,
    CONTRAST: 1.45,
    AMBIENT_LIGHT_INTENSITY: 0.05,
    DIR_LIGHT_INTENSITY: 2.8,
    SHADOW_MAP_SIZE: 1024,
    SHADOW_BLUR_KERNEL: 16,
    SHADOW_DARKNESS: 0.65
  },
  CAMERA: {
    DEFAULT_POS: { x: 0.0, y: 14.0, z: -38.0 },
    DEFAULT_TARGET: { x: 0.0, y: 14.0, z: 0.0 }
  }
} as const;
